### ISSUE TITLE
Spinner Control: duplicate paragraph

### ISSUE THREAD

**Issue by GLRsoftware** [VFPX/HelpFile#2]
There is a duplicate paragraph in the "Spinner Control" help page.

"The KeyBoardLowValue and SpinnerLowValue properties specify the minimum numeric values that can be entered from the keyboard into the spinner box and by clicking the arrow buttons on the spinner."

**Comment by FrancisFaure** [comment]
Hi GLRsoftware,
the first paragraph is for "KeyBoard**High**Value and Spinner**High**Value properties
the 2 paragraph is for "KeyBoard**Low**Value and Spinner**Low**Value properties
with best Regards
Francis
