### ISSUE TITLE
define which types are valid in AS clause on LOCAL, FUNCTION, LPARAMETERS, etc

### ISSUE THREAD

**Issue by isidroco** [VFPX/HelpFile#47]
couldn't find a list of valid AS types (ie: Boolean, Char, Byte, Numeric, Double, String, longInt, Integer, ...), the list and a link in those commands would be very useful, as I'm not sure which of them are valid in VFP

**Comment by DougHennig** [comment]
The "Visual FoxPro Data and Field Types" topic lists the data types.

**Comment by lscheffler** [comment]
Basically you can write what you like. It's kind of an inline comment.
```
local;
bla as blub

?bla
```
works flawless.

There is a restriction for PARAMETERS and LPARAMETERS in methods inherited.
If the string in the parent is to long, it is truncated in the child method. At least it was so as we started with the AS clause, I never retried.

Only class-definitions are of any value - intellisense respects it.

----
Anyway, a good hint is the stuff you see in the original intellisense table for the AS clause, it lists the types and the base classes.

**Comment by isidroco** [comment]
Thanks for your answer, was hoping to make strict type checking as in pascal to find errors on compilation (ie: avoiding function calls with wrong type). But unfortunately most of those errors appear on runtime, sometimes discovered by endusers which is very bad. It's a pity that Fox isn't stricter to avoid those situations. Because of that sometimes I add extra code to check varType on functions init.

**Comment by DougHennig** [comment]
VFP does not support strict typing. Using AS on a variable is for IntelliSense only.

**Comment by lscheffler** [comment]
> Thanks for your answer, was hoping to make strict type checking as in pascal to find errors on compilation (ie: avoiding function calls with wrong type). But unfortunately most of those errors appear on runtime, sometimes discovered by endusers which is very bad. It's a pity that Fox isn't stricter to avoid those situations. Because of that sometimes I add extra code to check varType on functions init.

@isidroco Common solution is to use _Hungarian notation_ and use it strict. No reuse of variables. It's bad practice to smear variables, even if one could.   
For function (...) calls  usually there is no other way then PCOUNT() and type checking, in special since one can skip parameters. In fact, it's good practice in VFP to test any parameter and provide a default or error out.
